
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./Nav"
import CustomThemeProvider from "./(components)/darkmode/custom-theme-provider"
import { CssBaseline } from "@mui/material";
import Sidebar from './sidebar';
import { Box, Typography} from '@mui/material';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
       <CustomThemeProvider>
        
        <Box sx={{ display: 'flex' }}>
        <CssBaseline/>
        <Sidebar/>
        <Typography className='w-[100%]'>
        <Nav/>
       {children}
        </Typography>
    </Box>
       </CustomThemeProvider>
        </body>
    </html>
  );
}
